public class DragDropMainController {
    
        @AuraEnabled
    public static void serverEcho(Contact c) {	 
        	System.debug('testttttttt');
        
        	/*Event evt = New Event();
        evt.OwnerId = '0056F000009Afjn';
        evt.StartDateTime = Date.newInstance(2018, 07, 12);
        evt.EndDateTime = Date.newInstance(2018, 07, 12);
        evt.WhoId = '0036F00002XOnyS';
        evt.WhatId = c.Id;
        evt.Subject = 'Call';
        insert evt;*/
       	//QuickAction.QuickActionRequest req = new QuickAction.QuickActionRequest();
        //req.quickActionName = QuickAction.describeQuickActions(List<String> actions);
        //return req.;
        	//req.record = evt;
            //QuickAction.QuickActionResult res = QuickAction.performQuickAction(req);
            //return ('Hello from the server, ');
	}

}